# Generated by Django 6.0.2 on 2026-02-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type', models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('SUPPLY', 'SUPPLY'), ('IMPROVEMENT', 'IMPROVEMENT')], max_length=12, null=True)),
                ('mode', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('PRACTICAL', 'PRACTICAL')], max_length=10, null=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_code', models.CharField(blank=True, choices=[('FN', 'FN'), ('AN', 'AN')], max_length=2, null=True)),
            ],
            options={
                'db_table': 'exam_slot',
                'indexes': [models.Index(fields=['exam_date', 'slot_code'], name='exam_slot_exam_da_29e7c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam_date', 'start_time', 'end_time', 'slot_code'), name='uq_exam_slot_time')],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField()),
                ('exam_type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('SUPPLY', 'SUPPLY'), ('IMPROVEMENT', 'IMPROVEMENT')], max_length=12)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='masters.subject')),
                ('exam_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='operations.examslot')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_map', to='masters.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_map', to='masters.subject')),
            ],
            options={
                'db_table': 'faculty_subject',
            },
        ),
        migrations.CreateModel(
            name='InvigilationDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation', to='operations.examslot')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation', to='masters.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation', to='masters.room')),
            ],
            options={
                'db_table': 'invigilation_duty',
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='operations.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_allocations', to='masters.room')),
            ],
            options={
                'db_table': 'room_allocation',
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='masters.student')),
            ],
            options={
                'db_table': 'student_academic_data',
            },
        ),
        migrations.CreateModel(
            name='StudentExamMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('BACKLOG', 'BACKLOG'), ('IMPROVEMENT', 'IMPROVEMENT')], max_length=12)),
                ('status', models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('ATTENDED', 'ATTENDED'), ('ABSENT', 'ABSENT')], default='REGISTERED', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_map', to='operations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_map', to='masters.student')),
            ],
            options={
                'db_table': 'student_exam_map',
            },
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('seat_no', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='masters.room')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='operations.studentexammap')),
            ],
            options={
                'db_table': 'seating_plan',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], max_length=7)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_marked', to='masters.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='masters.room')),
                ('student_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='operations.studentexammap')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_map', to='masters.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_map', to='masters.subject')),
            ],
            options={
                'db_table': 'student_subject',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'semester', 'exam_type'], name='exam_academi_63b6b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(
                check=models.Q(('semester__gte', 1), ('semester__lte', 8)),
                name='chk_exam_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='facultysubject',
            constraint=models.CheckConstraint(
                check=models.Q(('semester__gte', 1), ('semester__lte', 8)),
                name='chk_fs_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='facultysubject',
            constraint=models.UniqueConstraint(fields=('faculty', 'subject', 'academic_year', 'semester'), name='uq_faculty_subject'),
        ),
        migrations.AddConstraint(
            model_name='roomallocation',
            constraint=models.UniqueConstraint(fields=('exam', 'room'), name='uq_exam_room'),
        ),
        migrations.AddConstraint(
            model_name='studentacademicdata',
            constraint=models.CheckConstraint(
                check=models.Q(('year__gte', 1), ('year__lte', 4)),
                name='chk_sad_year_1_4'),
        ),
        migrations.AddConstraint(
            model_name='studentacademicdata',
            constraint=models.CheckConstraint(
                check=models.Q(('semester__gte', 1), ('semester__lte', 8)),
                name='chk_sad_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='studentacademicdata',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'year', 'semester'), name='uq_sad_student_term'),
        ),
        migrations.AddIndex(
            model_name='studentexammap',
            index=models.Index(fields=['student'], name='student_exa_student_a60c07_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexammap',
            index=models.Index(fields=['exam'], name='student_exa_exam_id_fff223_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexammap',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='uq_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='seatingplan',
            constraint=models.UniqueConstraint(fields=('room', 'row_no', 'seat_no'), name='uq_room_seat'),
        ),
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.CheckConstraint(
                check=models.Q(('semester__gte', 1), ('semester__lte', 8)),
                name='chk_ss_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'academic_year', 'semester'), name='uq_student_subject'),
        ),
    ]
