# Generated by Django 6.0.2 on 2026-02-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_course'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faculty_course',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
        migrations.RemoveConstraint(
            model_name='facultysubject',
            name='chk_fs_sem_1_8',
        ),
        migrations.RemoveConstraint(
            model_name='facultysubject',
            name='uq_faculty_subject',
        ),
        migrations.RemoveConstraint(
            model_name='studentsubject',
            name='chk_ss_sem_1_8',
        ),
        migrations.RemoveConstraint(
            model_name='studentsubject',
            name='uq_student_subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.course'),
        ),
        migrations.AddField(
            model_name='facultycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_map', to='masters.course'),
        ),
        migrations.AddField(
            model_name='facultycourse',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_map', to='masters.faculty'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_map', to='masters.course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_map', to='masters.student'),
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='subject',
        ),
        migrations.AddConstraint(
            model_name='facultycourse',
            constraint=models.CheckConstraint(
                check=models.Q(('semester__gte', 1), ('semester__lte', 8)),
                name='chk_fs_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='facultycourse',
            constraint=models.UniqueConstraint(fields=('faculty', 'course', 'academic_year', 'semester'), name='uq_faculty_course'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.CheckConstraint(
                check=models.Q(('semester__gte', 1), ('semester__lte', 8)),
                name='chk_ss_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'academic_year', 'semester'), name='uq_student_course'),
        ),
        migrations.DeleteModel(
            name='FacultySubject',
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
    ]
