# Generated by Django 4.2.23 on 2026-02-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_course'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_map', to='masters.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_map', to='masters.faculty')),
            ],
            options={
                'db_table': 'faculty_course',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_map', to='masters.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_map', to='masters.student')),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='masters.course'),
        ),
        migrations.DeleteModel(
            name='FacultySubject',
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.CheckConstraint(check=models.Q(('semester__gte', 1), ('semester__lte', 8)), name='chk_ss_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'academic_year', 'semester'), name='uq_student_course'),
        ),
        migrations.AddConstraint(
            model_name='facultycourse',
            constraint=models.CheckConstraint(check=models.Q(('semester__gte', 1), ('semester__lte', 8)), name='chk_fs_sem_1_8'),
        ),
        migrations.AddConstraint(
            model_name='facultycourse',
            constraint=models.UniqueConstraint(fields=('faculty', 'course', 'academic_year', 'semester'), name='uq_faculty_course'),
        ),
    ]
