# Generated by Django 4.2.23 on 2026-02-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_facultycourse_studentcourse_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='chk_exam_sem_1_8',
        ),
        migrations.RemoveConstraint(
            model_name='facultycourse',
            name='chk_fs_sem_1_8',
        ),
        migrations.RemoveConstraint(
            model_name='studentacademicdata',
            name='chk_sad_sem_1_8',
        ),
        migrations.RemoveConstraint(
            model_name='studentcourse',
            name='chk_ss_sem_1_8',
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentacademicdata',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='semester',
            field=models.CharField(max_length=20),
        ),
    ]
