# Generated by Django 4.2.23 on 2026-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_exam_chk_exam_sem_1_8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='regulation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examslot',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(check=models.Q(('semester__isnull', False), models.Q(('semester', ''), _negated=True)), name='check_semester_not_empty'),
        ),
    ]
