# Generated by Django 4.2.23 on 2026-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_exam_regulation_examslot_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exam',
            name='exam_academi_63b6b5_idx',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='registration_type',
            field=models.CharField(default='regular', help_text='Type of registration (e.g., regular, supply, improvement)', max_length=20),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='exam_type',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='slot_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'semester'], name='exam_academi_e686ae_idx'),
        ),
    ]
