# Generated by Django 4.2.23 on 2026-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_examinations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examinations',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='start_date_before_end_date'),
        ),
    ]
