# Generated by Django 4.2.23 on 2026-02-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_examinations_start_date_before_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examslot',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='examslot',
            name='exam_id',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.exam'),
        ),
    ]
