# Generated by Django 4.2.23 on 2026-02-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_remove_examslot_exam_name_examslot_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examslot',
            name='exam_id',
        ),
        migrations.AddField(
            model_name='examslot',
            name='examination',
            field=models.ForeignKey(blank=True, db_column='examination_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.examinations'),
        ),
    ]
