# Generated by Django 4.2.23 on 2026-03-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_delete_subject_remove_faculty_email_room_room_type_and_more'),
        ('operations', '0008_remove_roomallocation_uq_exam_slot_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faculty_availability',
            },
        ),
        migrations.RemoveConstraint(
            model_name='examslot',
            name='uq_exam_slot_time',
        ),
        migrations.RemoveConstraint(
            model_name='roomallocation',
            name='uq_exam_room',
        ),
        migrations.RemoveConstraint(
            model_name='seatingplan',
            name='uq_room_seat',
        ),
        migrations.RemoveIndex(
            model_name='examslot',
            name='exam_slot_exam_da_29e7c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentcourse',
            name='student_cou_academi_8fb926_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentcourse',
            name='student_cou_semeste_c89eaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentcourse',
            name='student_cou_student_eaea11_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='exam',
        ),
        migrations.AddField(
            model_name='examslot',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examslot',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='exam_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='operations.examslot'),
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='exam_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='operations.examslot'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.faculty'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.studentexammap'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='regulation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examinations',
            name='academic_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='exam_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.examinations'),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='mode',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='slot_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.course'),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.faculty'),
        ),
        migrations.AlterField(
            model_name='invigilationduty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.faculty'),
        ),
        migrations.AlterField(
            model_name='invigilationduty',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.room'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.room'),
        ),
        migrations.AlterField(
            model_name='seatingplan',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.room'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='registration_type',
            field=models.CharField(default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.student'),
        ),
        migrations.AlterField(
            model_name='studentexammap',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.student'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_slot'], name='exam_exam_sl_aced21_idx'),
        ),
        migrations.AddIndex(
            model_name='examslot',
            index=models.Index(fields=['exam_date'], name='exam_slot_exam_da_fa3a32_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['academic_year', 'semester'], name='student_cou_academi_fd605e_idx'),
        ),
        migrations.AddConstraint(
            model_name='examslot',
            constraint=models.UniqueConstraint(fields=('exam_date', 'start_time', 'end_time', 'slot_code'), name='uq_exam_slot_time'),
        ),
        migrations.AddConstraint(
            model_name='invigilationduty',
            constraint=models.UniqueConstraint(fields=('exam_slot', 'faculty'), name='uq_faculty_once_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='invigilationduty',
            constraint=models.UniqueConstraint(fields=('exam_slot', 'room'), name='uq_room_once_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='roomallocation',
            constraint=models.UniqueConstraint(fields=('exam_slot', 'room'), name='uq_slot_room'),
        ),
        migrations.AddConstraint(
            model_name='seatingplan',
            constraint=models.UniqueConstraint(fields=('exam_slot', 'room', 'row_no', 'seat_no'), name='uq_slot_room_seat'),
        ),
        migrations.AddConstraint(
            model_name='seatingplan',
            constraint=models.UniqueConstraint(fields=('student_exam',), name='uq_student_single_seat'),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='exam_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_faculty', to='operations.examslot'),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.faculty'),
        ),
        migrations.AddConstraint(
            model_name='facultyavailability',
            constraint=models.UniqueConstraint(fields=('exam_slot', 'faculty'), name='uq_faculty_slot'),
        ),
    ]
