# Generated by Django 4.2.23 on 2026-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_examslot_exam_id_examslot_examination'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='check_semester_not_empty',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='exam_academi_e686ae_idx',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.AddField(
            model_name='examinations',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='examinations',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
