# Generated by Django 4.2.23 on 2026-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_course'),
        ('operations', '0002_facultycourse_studentcourse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
