# Generated by Django 4.2.23 on 2026-02-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_delete_subject_remove_faculty_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regulation',
            field=models.CharField(blank=True, help_text='Regulation (e.g., 2021, R19, etc.)', max_length=10, null=True),
        ),
    ]
