# Generated by Django 6.0.2 on 2026-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_department_dept_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
