# Generated by Django 4.2.23 on 2026-02-15 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_student_regulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text='Batch/Regulation code', max_length=20, unique=True)),
                ('admission_year', models.PositiveIntegerField(help_text='Year of admission')),
                ('grad_year', models.PositiveIntegerField(help_text='Year of graduation')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='regulation',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch/Regulation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='masters.batch'),
        ),
    ]
