# Generated by Django 6.0.2 on 2026-02-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_course'),
        ('operations', '0002_facultycourse_studentcourse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
