# Generated by Django 4.2.23 on 2026-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_batch_remove_student_regulation_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, help_text='Type of room (e.g., Lecture Hall, Lab, etc.)', max_length=30, null=True),
        ),
    ]
