from django.urls import path
from . import views, ajax

app_name = "operations"

urlpatterns = [
    path("attendence/", views.attendence, name="attendence"),
    path("exams/", views.exams, name="exams"),
    path("room_alloc_view/", views.room_alloc_view, name="room_alloc_view"),
    path("roomalloc/", views.roomalloc, name="roomalloc"),
    path("roomalloc/content/", views.roomalloc_content, name="roomalloc_content"),
    path("report/", views.report, name="report"),
    path("exam-scheduling/<int:slot_id>/", views.exam_scheduling, name="schedule_exam"),
    path("exam_rooms_alloc/", views.exam_rooms_alloc, name="exam_rooms_alloc"),
    path("exam_faculty_alloc/", views.exam_faculty_alloc, name="exam_faculty_alloc"),
    path("ajax/exam-scheduling/groups/", ajax.ajax_exam_scheduling_groups, name="ajax_exam_scheduling_groups"),
    path("ajax/exam-scheduling/filters/", ajax.ajax_exam_filters, name="ajax_exam_filters"),
    path("ajax_exam_slots/", ajax.ajax_exam_slots, name="ajax_exam_slots"),
    path("examination/", views.examination, name="examination"),
    path("ajax/check_exam_publishable/", ajax.ajax_check_exam_publishable, name="ajax_check_exam_publishable"),
    path("ajax/examinations/", views.ajax_examinations, name="ajax_examinations"),
    path("ajax/delete-examination/", ajax.ajax_delete_examination, name="ajax_delete_examination"),
    path("ajax/edit-examination/", ajax.ajax_edit_examination, name="ajax_edit_examination"),
    path("ajax/edit-exam-slot/", ajax.ajax_edit_exam_slot, name="ajax_edit_exam_slot"),
    path("ajax/slot-courses/", ajax.ajax_slot_courses, name="ajax_slot_courses"),
    path("ajax/slot-rooms/", ajax.ajax_slot_rooms, name="ajax_slot_rooms"),
    path("ajax/slot-faculty/", ajax.ajax_slot_faculty, name="ajax_slot_faculty"),
    path("ajax/publish_exam/", ajax.ajax_publish_exam, name="ajax_publish_exam"),
    path("ajax/unpublish_exam/", ajax.ajax_unpublish_exam, name="ajax_unpublish_exam"),
    path("ajax/lock_exam/", ajax.ajax_lock_exam, name="ajax_lock_exam"),
    path("ajax/unlock_exam/", ajax.ajax_unlock_exam, name="ajax_unlock_exam"),
    path("ajax/generate-seating-plan/", views.ajax_generate_seating_plan, name="ajax_generate_seating_plan"),
    path("ajax/seating-plan/", views.ajax_seating_plan, name="ajax_seating_plan"),
    path("seatingplan/", views.seatingplan, name="seatingplan"),
    path("mark_attendance/", views.mark_attendance, name="mark_attendance"),
    path("reports/timetable/", views.report_timetable, name="report_timetable"),
    path("reports/room-occupancy/", views.report_room_occupancy, name="report_room_occupancy"),
    path("reports/student-coursereg/", views.report_student_coursereg, name="report_student_coursereg"),
    path("reports/invigilation/", views.report_invigilation, name="report_invigilation"),
    path("reports/master-seating/", views.report_master_seating, name="report_master_seating"),
    path("reports/attendance/", views.report_attendance, name="report_attendance"),
]
