# Generated by Django 6.0.2 on 2026-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_department_user_dept_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='dept',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD'), ('faculty', 'Faculty'), ('student', 'Student'), ('dept_exam_controller', 'Dept Exam Controller')], default='student', max_length=30),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
