# Generated by Django 4.2.23 on 2026-02-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_department_user_user_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_code',
        ),
    ]
